# See this guide for more settings:
#
# http://about.travis-ci.org/docs/user/build-configuration/

# See this guide for more settings:
#
# http://about.travis-ci.org/docs/user/build-configuration/

language: clojure
script: lein sub junit
before_install: lein sub install
jdk:
  - openjdk8
dist: trusty
notifications:
  email:
    - rivers@criteo.com
